### ISSUE TITLE
Examples not working ?

### ISSUE THREAD

**Issue by gnicol-bzh** [mjurczyk/grunt-galen#5]
Hello,

I've been unable to run your examples (under Windows 7).

I've installed Galen from [galenframework.com](http://galenframework.com/), `galen --version` returns 

``` Batchfile
Galen Framework
Version: 1.6.3
JavaScript executor: Rhino 1.7 release 5 2015 01 29
```

I copied your `example` folder, I've chosen the _static file test_, then in that folder:

``` Batchfile
npm install
grunt
```

and it returns

``` Batchfile
Running "connect:server" (connect) task
Started connect web server on http://localhost:3000

Running "galen:local" (galen) task
Starting Galen.
   • test/sample.test.js done


passed 0 test(s) [0%]

Done, without errors.
```

Tests are ignored, even when introducing weird spec. 

I've also tried `galen config' to add the`config` file, but it changes nothing.

PS: I also have problem with my own tests on my own project, but I prefer start with your examples, to be sure I didn't forget something ;)

**Comment by mjurczyk** [comment]
Apologies, examples have been deprecated and I didn't update them to the current version. Taking care of it right away.

**Comment by mjurczyk** [comment]
@gnicol-bzh adjusted examples for the newest version of `grunt-galen`. Please download/update to the latest version and run `npm install && grunt` in a desired example directory - it should work just fine right now ;)

**Comment by gnicol-bzh** [comment]
Thank you. Everything seems ok now! :)
Time to see what's wrong with my own work now :p... I'm closing this issue.

_PS: reflecting the changes on my own tests, my tests passed._
